### ISSUE TITLE
Glowroot Transaction aggregation does not work in version 0.14.2

### ISSUE THREAD

**Issue by yasinsula061** [glowroot/glowroot#1090]
Hi,
Fİrst of all, thank you for your efforts and application.

 I have upgraded my Glowroot central application and agents from version 0.13.6 to version 0.14.2.
In the selection of services in Transaction, data flow is not studied in the collection of rollup value. (queries, thread profile, response time,service call). But when I select agent id instead of roll up, the stream comes in. This is an important problem, do you have any suggestions for solving it?

![image](https://github.com/glowroot/glowroot/assets/69668200/bb0dcf73-0dd6-4d48-b91d-61a0fa044590)

**Comment by lfen21** [comment]
Same issue

**Comment by gregsting** [comment]
Same issue here, is there any hope to fix? Slowtraces are garegated but not the rest. Could be that the agents needs to be updated too?

**Comment by yasinsula061** [comment]
Hi,
The upgrade for the collector and agent is version 0.14.3 beta 5.

**Comment by Nowheresly** [comment]
maybe could you try to take several thread dumps of glowroot central in order to understand why the thread in charge of generating rollups seems to be stuck?

**Comment by Nowheresly** [comment]
it should be fixed with the latest version  https://github.com/glowroot/glowroot/releases/tag/v0.14.5-beta.3

**Comment by gregsting** [comment]
Hello, thanks for following up on this. It's still not working but I have some rollups working and other not or maybe these are delayed. I tested for +- 20 minutes and got one cassandra timeout (the environement is very quiet now as it's saturday night)

I rolled back to 13.6 and rollups immediately showed up, so I'm not even sure it's not a display problem?

I took a thread dump this time

[threaddump.log](https://github.com/user-attachments/files/25999469/threaddump.log)

**Comment by Never-lab** [comment]
## Analysis note (Central rollup / agent-group views)

### Symptom (from reports)
- Leaf **agent id** views show transaction data (response time, queries, service calls, profile).
- Selecting an **agent rollup / group** shows empty or stale charts for those same series.
- Slow traces sometimes still appear aggregated.
- Multiple reporters (0.14.2 through 0.14.6) also see **Cassandra timeouts** / lower C* CPU while Central is "stuck" not producing rollups.
- Rolling Central back to **0.13.6** restored rollup charts for some (even for periods when a newer Central had been running) -- suggests write/read path or rollup worker health more than "agents never sent data".

### What this is (and is not)
This is primarily a **Central collector rollup + Cassandra capacity / timeout** problem, not a missing UI chart for leaf agents.

Relevant code area: `central/.../RollupService.java` and aggregate rollup DAOs. Maintainers already shipped several rollup/timeout hardening commits across 0.14.5-0.14.6 betas (`split rollup compute by type`, better exception handling, driver profile / timeout fixes). Thread dumps shared earlier showed **no deadlock** -- consistent with work failing or backing off under C* pressure rather than a lock.

### What we still need to confirm on current builds
Please retest on matching **agent + Central [0.14.7](https://github.com/glowroot/glowroot/releases/tag/v0.14.7)** (or newer beta) with:
1. Central log excerpts around rollup / Cassandra timeout (not only UI).
2. Whether **all** rollup groups fail or only deep/busy branches (e.g. `Prod::Jboss`).
3. C* sizing (CPU, compaction, tombstones) vs agent count -- same family as other Central capacity reports.

If 0.14.7 still fails on a quiet lab cluster with a fresh keyspace, that is the strongest signal for another code fix. If it only fails on large historical keyspaces under timeout, the next lever is C* capacity / retention / starting clean (config export) rather than a UI change.

cc @nowheresly -- we will dig for a concrete code gap vs capacity; happy to take a targeted PR if a clear defect remains on 0.14.7+.

**Comment by Never-lab** [comment]
Follow-up after a code pass on current main / 0.14.7 line:

- Group transaction charts are filled by Central `RollupService` + `AggregateDaoImpl.rollupFromChildren` (parent ids ending in `::`), not by the UI inventing aggregates from leaf agents.
- Known race that emptied group query/profile/service-call series was fixed in 0.14.4 (`ab0291dd2` / #1036) and time-rollup compose in 0.14.5 (`b2cfc6dc5`); 0.14.6+ adds rollup isolation/logging; 0.14.7 switches C* load control to execution profiles (`efcbeb9d2`).
- No clear remaining code defect found that would empty only rollup views while leaf agents stay OK; symptoms still match Cassandra timeout / rollup backlog under load.
- Please retest matching agent + Central **v0.14.7** (or newer): (1) Central log lines for rollup / DriverTimeout / WriteTimeout; (2) whether only heavy branches fail; (3) if possible, quiet lab with fresh keyspace (keep config export) vs long-lived upgraded keyspace.
- If 0.14.7 still fails on a quiet fresh keyspace, share Central logs + one thread dump during empty group charts -- that is the gate for another code fix / PR. If it only fails on large historical clusters with timeouts, next levers are C* capacity, retention/compaction, and reducing rollup backlog rather than a UI change.

cc @nowheresly
