### ISSUE TITLE
Central Collector gauges not reflecting configuration changes

### ISSUE THREAD

**Issue by carl-payne** [glowroot/glowroot#294]
Using Glowroot version 0.9.26 central collector configuration

Have successfully monitored a JVM running Java 8 G1 Garbage Collection using the following gauges:

java.lang / GarbageCollector / * 
CollectionCount 
CollectionTime 

java.lang / MemoryPool / * 
Usage.used 

Got the following JVM output as expected for G1:

 java.lang / GarbageCollector / G1 Old Generation / CollectionCount  
 java.lang / GarbageCollector / G1 Old Generation / CollectionTime  
 java.lang / GarbageCollector / G1 Young Generation / CollectionCount  
 java.lang / GarbageCollector / G1 Young Generation / CollectionTime  
 
 java.lang / Memory / HeapMemoryUsage / used  
 java.lang / MemoryPool / Code Cache / Usage / used  
 java.lang / MemoryPool / Compressed Class Space / Usage / used  
 java.lang / MemoryPool / G1 Eden Space / Usage / used  
 java.lang / MemoryPool / G1 Old Gen / Usage / used  
 java.lang / MemoryPool / G1 Survivor Space / Usage / used  
 java.lang / MemoryPool / Metaspace / Usage / used   
 
However, changed the same JVM to use ConcurrentMarkSweep (CMS) Garbage Collection and restarted JVM,  using the same gauges:

java.lang / GarbageCollector / * 
CollectionCount 
CollectionTime 

java.lang / MemoryPool / * 
Usage.used 

Still get the JVM output for G1 and not CMS, for which I would have expected to see the following:

 java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionCount 
 java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionTime   
 java.lang / GarbageCollector / ParNew / CollectionCount  
 java.lang / GarbageCollector / ParNew / CollectionTime   

 java.lang / Memory / HeapMemoryUsage / used
 java.lang / MemoryPool / CMS Old Gen / Usage / used  
 java.lang / MemoryPool / Code Cache / Usage / used   
 java.lang / MemoryPool / Metaspace / Usage / used  
 java.lang / MemoryPool / Par Eden Space / Usage / used  
 java.lang / MemoryPool / Par Survivor Space / Usage / used  
 
Please review and advise

**Comment by trask** [comment]
Hi @carl-payne, thanks for reporting this!  I happened to run into the same issue myself a couple of days ago (161218376179382b4c3417c81116d399606c7622) and it is fixed in the latest release 0.9.28.

**Comment by carl-payne** [comment]
Hi Trask

Firstly thanks for your quick response

I have download and applied glowroot version 0.9.28 agent and central collector successfully to my environment

However, having reviewed reported issue I now do see the missing CMS gauges, some that are common to both CMS and G1, but also see the old G1 gauges as well (see below):

CMS - java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionCount
CMS - java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionTime

G1 - java.lang / GarbageCollector / G1 Old Generation / CollectionCount
G1 - java.lang / GarbageCollector / G1 Old Generation / CollectionTime
G1 - java.lang / GarbageCollector / G1 Young Generation / CollectionCount
G1 - java.lang / GarbageCollector / G1 Young Generation / CollectionTime

CMS - java.lang / GarbageCollector / ParNew / CollectionCount
CMS - java.lang / GarbageCollector / ParNew / CollectionTime

Common - java.lang / Memory / HeapMemoryUsage / used
CMS - java.lang / MemoryPool / CMS Old Gen / Usage / used
Common - java.lang / MemoryPool / Code Cache / Usage / used

G1 - java.lang / MemoryPool / Compressed Class Space / Usage / used
G1 - java.lang / MemoryPool / G1 Eden Space / Usage / used
G1 - java.lang / MemoryPool / G1 Old Gen / Usage / used
G1 - java.lang / MemoryPool / G1 Survivor Space / Usage / used

Common - java.lang / MemoryPool / Metaspace / Usage / used
CMS - java.lang / MemoryPool / Par Eden Space / Usage / used
CMS - java.lang / MemoryPool / Par Survivor Space / Usage / used

I think this is quite confusing and may be related to existing issues #155 and #195

Please review and advise

**Comment by carl-payne** [comment]
Sorry closed in error

**Comment by trask** [comment]
Hi @carl-payne, #195 is fixed now in the latest snapshot release [glowroot-agent-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.29-SNAPSHOT).  Hopefully that should resolve the confusion. Let me know if you are still seeing anything unusual after that.  Thanks.

**Comment by carl-payne** [comment]
Hi Trask

I have download and applied glowroot version 0.9.29 agent successfully to my environment

However, having reviewed reported issue I still see all of the gauges I did with version 0.9.28 (see below):

CMS - java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionCount
CMS - java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionTime

G1 - java.lang / GarbageCollector / G1 Old Generation / CollectionCount
G1 - java.lang / GarbageCollector / G1 Old Generation / CollectionTime
G1 - java.lang / GarbageCollector / G1 Young Generation / CollectionCount
G1 - java.lang / GarbageCollector / G1 Young Generation / CollectionTime

CMS - java.lang / GarbageCollector / ParNew / CollectionCount
CMS - java.lang / GarbageCollector / ParNew / CollectionTime

Common - java.lang / Memory / HeapMemoryUsage / used
CMS - java.lang / MemoryPool / CMS Old Gen / Usage / used
Common - java.lang / MemoryPool / Code Cache / Usage / used

G1 - java.lang / MemoryPool / Compressed Class Space / Usage / used
G1 - java.lang / MemoryPool / G1 Eden Space / Usage / used
G1 - java.lang / MemoryPool / G1 Old Gen / Usage / used
G1 - java.lang / MemoryPool / G1 Survivor Space / Usage / used

Common - java.lang / MemoryPool / Metaspace / Usage / used
CMS - java.lang / MemoryPool / Par Eden Space / Usage / used
CMS - java.lang / MemoryPool / Par Survivor Space / Usage / used

Please review and advise

**Comment by trask** [comment]
Hi @carl-payne, the old gauges will be displayed when you are looking at time periods that include days where they were collected (so you can still go back and look at old data for the old gauges).

I just updated the glowroot demo site with the latest snapshot release, and also switched it from running `-XX:+UseG1GC` to `-XX:+UseConcMarkSweepGC`.

When looking at a time period that covers today, you can see both G1 and CMS gauges since they were both collected at some point today, e.g. https://demo.glowroot.org/jvm/gauges?from=1512500400000&to=1512504000000

When looking at a time period that covers only yesterday (or before), you only see G1 gauges, e.g. https://demo.glowroot.org/jvm/gauges?from=1512414000000&to=1512417600000

Tomorrow (UTC time zone), when looking at a time period that covers only tomorrow (or after), you should only see the CMS gauges.

Let me know if this explains what you are seeing, or if you are still seeing something different locally.  Thanks.

**Comment by trask** [comment]
@carl-payne, I'm sorry, I just remembered you are using the central collector, but I pointed you to download the latest agent snapshot.  To get the fix for #195, you need to update to the latest central snapshot  [glowroot-central-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.9.29-SNAPSHOT) (or [glowroot-central-0.9.29-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.9.29-SNAPSHOT)).

**Comment by carl-payne** [comment]
Hi Trask

I have download and applied glowroot-central-0.9.29-20171205.081442-5-dist.zip successfully to my environment

Reviewed output and now see the only the following CMS gauges as expected:

java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionCount
java.lang / GarbageCollector / ConcurrentMarkSweep / CollectionTime
java.lang / GarbageCollector / ParNew / CollectionCount
java.lang / GarbageCollector / ParNew / CollectionTime

java.lang / Memory / HeapMemoryUsage / used
java.lang / MemoryPool / CMS Old Gen / Usage / used
java.lang / MemoryPool / Code Cache / Usage / used
java.lang / MemoryPool / Metaspace / Usage / used
java.lang / MemoryPool / Par Eden Space / Usage / used
java.lang / MemoryPool / Par Survivor Space / Usage / used

So please consider this issue resolved

Thanks again for your prompt response, it's really appreciated, keep up the good work

Regards
Carl
